import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import Footer from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">      
      <body 
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
        style={{
          backgroundColor: "var(--body-bg)",
          opacity:"var(--body-op)"         
        }}
        >        
        <div 
          className="flex flex-col min-h-screen sm:p-2 font-[family-name:var(--font-geist-sans)] border-custom"
          style={{
            borderWidth: "var(--border-width-div)",
            borderColor: "var(--border-color-div)"             
          }}
        >          
          <Sidebar />          
          <main 
            className="flex-1 p-3 md:p-3 border-custom"   
            style={{
              borderWidth: "var(--border-width-main)",
              borderColor: "var(--border-color-main)"             
            }}
          >                     
            {children}            
          </main>     
          <Footer/> 
        </div>
      </body>
    </html>
  );
}
